/*
 * KLCubeLHDN MyInvois Middleware API
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for DocumentPdfResponse
 */
class DocumentPdfResponseTest {
    private final DocumentPdfResponse model = new DocumentPdfResponse();

    /**
     * Model tests for DocumentPdfResponse
     */
    @Test
    void testDocumentPdfResponse() {
        // TODO: test DocumentPdfResponse
    }

    /**
     * Test the property 'uuid'
     */
    @Test
    void uuidTest() {
        // TODO: test uuid
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'document'
     */
    @Test
    void documentTest() {
        // TODO: test document
    }

    /**
     * Test the property 'format'
     */
    @Test
    void formatTest() {
        // TODO: test format
    }

    /**
     * Test the property 'message'
     */
    @Test
    void messageTest() {
        // TODO: test message
    }

}
