/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.myinvois.sdk.model.DocumentVersion;
import com.myinvois.sdk.model.Environment;
import com.myinvois.sdk.model.Mode;
import java.time.OffsetDateTime;
import java.util.Arrays;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Session
 */
class SessionTest {
    private final Session model = new Session();

    /**
     * Model tests for Session
     */
    @Test
    void testSession() {
        // TODO: test Session
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'env'
     */
    @Test
    void envTest() {
        // TODO: test env
    }

    /**
     * Test the property 'mode'
     */
    @Test
    void modeTest() {
        // TODO: test mode
    }

    /**
     * Test the property 'onBehalfOf'
     */
    @Test
    void onBehalfOfTest() {
        // TODO: test onBehalfOf
    }

    /**
     * Test the property 'documentVersion'
     */
    @Test
    void documentVersionTest() {
        // TODO: test documentVersion
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'expiresAt'
     */
    @Test
    void expiresAtTest() {
        // TODO: test expiresAt
    }

}
