/*
 * HashLHDN MyInvois Middleware API
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Client:** Hashmato | **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.myinvois.sdk.model.BuyerInfo;
import com.myinvois.sdk.model.InvoiceItem;
import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmitBuyerRequestInvoice
 */
class SubmitBuyerRequestInvoiceTest {
    private final SubmitBuyerRequestInvoice model = new SubmitBuyerRequestInvoice();

    /**
     * Model tests for SubmitBuyerRequestInvoice
     */
    @Test
    void testSubmitBuyerRequestInvoice() {
        // TODO: test SubmitBuyerRequestInvoice
    }

    /**
     * Test the property 'invoiceNumber'
     */
    @Test
    void invoiceNumberTest() {
        // TODO: test invoiceNumber
    }

    /**
     * Test the property 'invoiceDate'
     */
    @Test
    void invoiceDateTest() {
        // TODO: test invoiceDate
    }

    /**
     * Test the property 'amount'
     */
    @Test
    void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'discount'
     */
    @Test
    void discountTest() {
        // TODO: test discount
    }

    /**
     * Test the property 'rounding'
     */
    @Test
    void roundingTest() {
        // TODO: test rounding
    }

    /**
     * Test the property 'taxAmount'
     */
    @Test
    void taxAmountTest() {
        // TODO: test taxAmount
    }

    /**
     * Test the property 'total'
     */
    @Test
    void totalTest() {
        // TODO: test total
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'items'
     */
    @Test
    void itemsTest() {
        // TODO: test items
    }

}
