/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.myinvois.sdk.model.DocumentInput;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for SubmissionCreateRequest
 */
class SubmissionCreateRequestTest {
    private final SubmissionCreateRequest model = new SubmissionCreateRequest();

    /**
     * Model tests for SubmissionCreateRequest
     */
    @Test
    void testSubmissionCreateRequest() {
        // TODO: test SubmissionCreateRequest
    }

    /**
     * Test the property 'sessionId'
     */
    @Test
    void sessionIdTest() {
        // TODO: test sessionId
    }

    /**
     * Test the property 'documents'
     */
    @Test
    void documentsTest() {
        // TODO: test documents
    }

    /**
     * Test the property 'autoMinify'
     */
    @Test
    void autoMinifyTest() {
        // TODO: test autoMinify
    }

    /**
     * Test the property 'asyncPolling'
     */
    @Test
    void asyncPollingTest() {
        // TODO: test asyncPolling
    }

}
