# coding: utf-8

"""
    MyInvois Middleware Gateway

    Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class SigningErrorPhase(str, Enum):
    """
    Phase where signing error occurred
    """

    """
    allowed enum values
    """
    LOADING = 'loading'
    SIGNING = 'signing'
    VERIFICATION = 'verification'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of SigningErrorPhase from a JSON string"""
        return cls(json.loads(json_str))


