/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using MyInvois.Sdk.Client;
using MyInvois.Sdk.Model;

namespace MyInvois.Sdk.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxpayerApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Validate taxpayer TIN
        /// </summary>
        /// <remarks>
        /// Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </remarks>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TinValidationResponse</returns>
        TinValidationResponse ValidateTin(string sessionId, string tin, string idType, string idValue, int operationIndex = 0);

        /// <summary>
        /// Validate taxpayer TIN
        /// </summary>
        /// <remarks>
        /// Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </remarks>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TinValidationResponse</returns>
        ApiResponse<TinValidationResponse> ValidateTinWithHttpInfo(string sessionId, string tin, string idType, string idValue, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxpayerApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Validate taxpayer TIN
        /// </summary>
        /// <remarks>
        /// Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </remarks>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TinValidationResponse</returns>
        System.Threading.Tasks.Task<TinValidationResponse> ValidateTinAsync(string sessionId, string tin, string idType, string idValue, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// Validate taxpayer TIN
        /// </summary>
        /// <remarks>
        /// Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </remarks>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TinValidationResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TinValidationResponse>> ValidateTinWithHttpInfoAsync(string sessionId, string tin, string idType, string idValue, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxpayerApi : ITaxpayerApiSync, ITaxpayerApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TaxpayerApi : ITaxpayerApi
    {
        private MyInvois.Sdk.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxpayerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaxpayerApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxpayerApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaxpayerApi(string basePath)
        {
            this.Configuration = MyInvois.Sdk.Client.Configuration.MergeConfigurations(
                MyInvois.Sdk.Client.GlobalConfiguration.Instance,
                new MyInvois.Sdk.Client.Configuration { BasePath = basePath }
            );
            this.Client = new MyInvois.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MyInvois.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = MyInvois.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxpayerApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TaxpayerApi(MyInvois.Sdk.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = MyInvois.Sdk.Client.Configuration.MergeConfigurations(
                MyInvois.Sdk.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new MyInvois.Sdk.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new MyInvois.Sdk.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = MyInvois.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxpayerApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TaxpayerApi(MyInvois.Sdk.Client.ISynchronousClient client, MyInvois.Sdk.Client.IAsynchronousClient asyncClient, MyInvois.Sdk.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = MyInvois.Sdk.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public MyInvois.Sdk.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public MyInvois.Sdk.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public MyInvois.Sdk.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public MyInvois.Sdk.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Validate taxpayer TIN Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </summary>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TinValidationResponse</returns>
        public TinValidationResponse ValidateTin(string sessionId, string tin, string idType, string idValue, int operationIndex = 0)
        {
            MyInvois.Sdk.Client.ApiResponse<TinValidationResponse> localVarResponse = ValidateTinWithHttpInfo(sessionId, tin, idType, idValue);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate taxpayer TIN Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </summary>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TinValidationResponse</returns>
        public MyInvois.Sdk.Client.ApiResponse<TinValidationResponse> ValidateTinWithHttpInfo(string sessionId, string tin, string idType, string idValue, int operationIndex = 0)
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'sessionId' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'tin' is set
            if (tin == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'tin' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'idType' is set
            if (idType == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'idType' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'idValue' is set
            if (idValue == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'idValue' when calling TaxpayerApi->ValidateTin");
            }

            MyInvois.Sdk.Client.RequestOptions localVarRequestOptions = new MyInvois.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MyInvois.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MyInvois.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "sessionId", sessionId));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "tin", tin));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "idType", idType));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "idValue", idValue));

            localVarRequestOptions.Operation = "TaxpayerApi.ValidateTin";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<TinValidationResponse>("/v1/tin/validate", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValidateTin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Validate taxpayer TIN Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </summary>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TinValidationResponse</returns>
        public async System.Threading.Tasks.Task<TinValidationResponse> ValidateTinAsync(string sessionId, string tin, string idType, string idValue, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            MyInvois.Sdk.Client.ApiResponse<TinValidationResponse> localVarResponse = await ValidateTinWithHttpInfoAsync(sessionId, tin, idType, idValue, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Validate taxpayer TIN Validates a taxpayer&#39;s TIN against MyInvois. Results are cached to reduce API calls. 
        /// </summary>
        /// <exception cref="MyInvois.Sdk.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="sessionId">Gateway session ID</param>
        /// <param name="tin">Tax Identification Number</param>
        /// <param name="idType">ID type for validation</param>
        /// <param name="idValue">ID value corresponding to idType</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TinValidationResponse)</returns>
        public async System.Threading.Tasks.Task<MyInvois.Sdk.Client.ApiResponse<TinValidationResponse>> ValidateTinWithHttpInfoAsync(string sessionId, string tin, string idType, string idValue, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'sessionId' is set
            if (sessionId == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'sessionId' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'tin' is set
            if (tin == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'tin' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'idType' is set
            if (idType == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'idType' when calling TaxpayerApi->ValidateTin");
            }

            // verify the required parameter 'idValue' is set
            if (idValue == null)
            {
                throw new MyInvois.Sdk.Client.ApiException(400, "Missing required parameter 'idValue' when calling TaxpayerApi->ValidateTin");
            }


            MyInvois.Sdk.Client.RequestOptions localVarRequestOptions = new MyInvois.Sdk.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = MyInvois.Sdk.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = MyInvois.Sdk.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "sessionId", sessionId));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "tin", tin));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "idType", idType));
            localVarRequestOptions.QueryParameters.Add(MyInvois.Sdk.Client.ClientUtils.ParameterToMultiMap("", "idValue", idValue));

            localVarRequestOptions.Operation = "TaxpayerApi.ValidateTin";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TinValidationResponse>("/v1/tin/validate", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ValidateTin", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
