# coding: utf-8

"""
    MyInvois Middleware Gateway

    Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.document_list_item import DocumentListItem

class TestDocumentListItem(unittest.TestCase):
    """DocumentListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DocumentListItem:
        """Test DocumentListItem
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DocumentListItem`
        """
        model = DocumentListItem()
        if include_optional:
            return DocumentListItem(
                uuid = '',
                submission_uid = '',
                long_id = '',
                internal_id = '',
                type_name = '',
                type_version_name = '',
                issuer_tin = '',
                issuer_name = '',
                receiver_id = '',
                receiver_name = '',
                date_time_issued = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_time_received = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                date_time_validated = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                total_payable_amount = '',
                status = '',
                cancel_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                reject_date_time = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DocumentListItem(
                uuid = '',
                submission_uid = '',
                internal_id = '',
                type_name = '',
                issuer_tin = '',
                status = '',
        )
        """

    def testDocumentListItem(self):
        """Test DocumentListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
