# coding: utf-8

"""
    KLCubeLHDN MyInvois Middleware API

    API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 

    The version of the OpenAPI document: 1.1.1
    Contact: hello@zahidaramai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.create_company_request import CreateCompanyRequest

class TestCreateCompanyRequest(unittest.TestCase):
    """CreateCompanyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateCompanyRequest:
        """Test CreateCompanyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateCompanyRequest`
        """
        model = CreateCompanyRequest()
        if include_optional:
            return CreateCompanyRequest(
                name = '',
                tin = '',
                id_type = 'BRN',
                id_value = '',
                address = '',
                city = '',
                state = '',
                postal_code = '',
                phone = '',
                email = '',
                myinvois_env = 'SANDBOX'
            )
        else:
            return CreateCompanyRequest(
                name = '',
                tin = '',
                id_type = 'BRN',
                id_value = '',
        )
        """

    def testCreateCompanyRequest(self):
        """Test CreateCompanyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
