# coding: utf-8

"""
    KLCubeLHDN MyInvois Middleware API

    API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 

    The version of the OpenAPI document: 1.1.1
    Contact: hello@zahidaramai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.list_all_companies200_response import ListAllCompanies200Response

class TestListAllCompanies200Response(unittest.TestCase):
    """ListAllCompanies200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAllCompanies200Response:
        """Test ListAllCompanies200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAllCompanies200Response`
        """
        model = ListAllCompanies200Response()
        if include_optional:
            return ListAllCompanies200Response(
                data = [
                    myinvois_sdk.models.company.Company(
                        id = '', 
                        name = '', 
                        tin = '', 
                        id_type = '', 
                        id_value = '', 
                        address = '', 
                        city = '', 
                        state = '', 
                        postal_code = '', 
                        phone = '', 
                        email = '', 
                        is_active = True, 
                        myinvois_env = 'SANDBOX', 
                        has_credentials = True, 
                        created_at = '', 
                        updated_at = '', )
                    ]
            )
        else:
            return ListAllCompanies200Response(
        )
        """

    def testListAllCompanies200Response(self):
        """Test ListAllCompanies200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
