# coding: utf-8

"""
    MyInvois Middleware Gateway

    Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.session_create_request import SessionCreateRequest

class TestSessionCreateRequest(unittest.TestCase):
    """SessionCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SessionCreateRequest:
        """Test SessionCreateRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SessionCreateRequest`
        """
        model = SessionCreateRequest()
        if include_optional:
            return SessionCreateRequest(
                env = 'PROD',
                mode = 'INTERMEDIARY',
                client_id = '0',
                client_secret = '0',
                document_version = '1.0',
                on_behalf_of = '80'
            )
        else:
            return SessionCreateRequest(
                env = 'PROD',
                mode = 'INTERMEDIARY',
                client_id = '0',
                client_secret = '0',
                on_behalf_of = '80',
        )
        """

    def testSessionCreateRequest(self):
        """Test SessionCreateRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
