# coding: utf-8

"""
    HashLHDN MyInvois Middleware API

    API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Client:** Hashmato | **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 

    The version of the OpenAPI document: 1.1.1
    Contact: hello@zahidaramai.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.delete_user200_response import DeleteUser200Response

class TestDeleteUser200Response(unittest.TestCase):
    """DeleteUser200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteUser200Response:
        """Test DeleteUser200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteUser200Response`
        """
        model = DeleteUser200Response()
        if include_optional:
            return DeleteUser200Response(
                message = ''
            )
        else:
            return DeleteUser200Response(
        )
        """

    def testDeleteUser200Response(self):
        """Test DeleteUser200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
