# coding: utf-8

"""
    MyInvois Middleware Gateway

    Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.models.signing_health_status import SigningHealthStatus

class TestSigningHealthStatus(unittest.TestCase):
    """SigningHealthStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SigningHealthStatus:
        """Test SigningHealthStatus
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SigningHealthStatus`
        """
        model = SigningHealthStatus()
        if include_optional:
            return SigningHealthStatus(
                enabled = True,
                certificate_valid = True,
                certificate_expiry = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                certificate_subject = '',
                default_version = '1.0',
                expiring_within30_days = True
            )
        else:
            return SigningHealthStatus(
        )
        """

    def testSigningHealthStatus(self):
        """Test SigningHealthStatus"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
