# coding: utf-8

"""
    MyInvois Middleware Gateway

    Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from myinvois_sdk.api.documents_api import DocumentsApi


class TestDocumentsApi(unittest.TestCase):
    """DocumentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DocumentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_document(self) -> None:
        """Test case for cancel_document

        Cancel a document
        """
        pass

    def test_get_document_details(self) -> None:
        """Test case for get_document_details

        Get document details
        """
        pass

    def test_reject_document(self) -> None:
        """Test case for reject_document

        Reject a document
        """
        pass


if __name__ == '__main__':
    unittest.main()
