/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MyInvois.Sdk.Client.OpenAPIDateConverter;

namespace MyInvois.Sdk.Model
{
    /// <summary>
    /// DocumentInput
    /// </summary>
    [DataContract(Name = "DocumentInput")]
    public partial class DocumentInput : IValidatableObject
    {
        /// <summary>
        /// Document format
        /// </summary>
        /// <value>Document format</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum FormatEnum
        {
            /// <summary>
            /// Enum XML for value: XML
            /// </summary>
            [EnumMember(Value = "XML")]
            XML = 1,

            /// <summary>
            /// Enum JSON for value: JSON
            /// </summary>
            [EnumMember(Value = "JSON")]
            JSON = 2
        }


        /// <summary>
        /// Document format
        /// </summary>
        /// <value>Document format</value>
        [DataMember(Name = "format", IsRequired = true, EmitDefaultValue = true)]
        public FormatEnum Format { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentInput" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DocumentInput() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentInput" /> class.
        /// </summary>
        /// <param name="format">Document format (required).</param>
        /// <param name="codeNumber">Invoice/document code number (required).</param>
        /// <param name="rawDocument">Raw document content (gateway will base64 encode and hash).</param>
        /// <param name="documentBase64">Pre-encoded base64 document.</param>
        /// <param name="documentHashSha256">Pre-computed SHA256 hash.</param>
        public DocumentInput(FormatEnum format = default(FormatEnum), string codeNumber = default(string), string rawDocument = default(string), byte[] documentBase64 = default(byte[]), string documentHashSha256 = default(string))
        {
            this.Format = format;
            // to ensure "codeNumber" is required (not null)
            if (codeNumber == null)
            {
                throw new ArgumentNullException("codeNumber is a required property for DocumentInput and cannot be null");
            }
            this.CodeNumber = codeNumber;
            this.RawDocument = rawDocument;
            this.DocumentBase64 = documentBase64;
            this.DocumentHashSha256 = documentHashSha256;
        }

        /// <summary>
        /// Invoice/document code number
        /// </summary>
        /// <value>Invoice/document code number</value>
        [DataMember(Name = "codeNumber", IsRequired = true, EmitDefaultValue = true)]
        public string CodeNumber { get; set; }

        /// <summary>
        /// Raw document content (gateway will base64 encode and hash)
        /// </summary>
        /// <value>Raw document content (gateway will base64 encode and hash)</value>
        [DataMember(Name = "rawDocument", EmitDefaultValue = false)]
        public string RawDocument { get; set; }

        /// <summary>
        /// Pre-encoded base64 document
        /// </summary>
        /// <value>Pre-encoded base64 document</value>
        [DataMember(Name = "documentBase64", EmitDefaultValue = false)]
        public byte[] DocumentBase64 { get; set; }

        /// <summary>
        /// Pre-computed SHA256 hash
        /// </summary>
        /// <value>Pre-computed SHA256 hash</value>
        [DataMember(Name = "documentHashSha256", EmitDefaultValue = false)]
        public string DocumentHashSha256 { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentInput {\n");
            sb.Append("  Format: ").Append(Format).Append("\n");
            sb.Append("  CodeNumber: ").Append(CodeNumber).Append("\n");
            sb.Append("  RawDocument: ").Append(RawDocument).Append("\n");
            sb.Append("  DocumentBase64: ").Append(DocumentBase64).Append("\n");
            sb.Append("  DocumentHashSha256: ").Append(DocumentHashSha256).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // CodeNumber (string) minLength
            if (this.CodeNumber != null && this.CodeNumber.Length < 1)
            {
                yield return new ValidationResult("Invalid value for CodeNumber, length must be greater than 1.", new [] { "CodeNumber" });
            }

            yield break;
        }
    }

}
