/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MyInvois.Sdk.Client.OpenAPIDateConverter;

namespace MyInvois.Sdk.Model
{
    /// <summary>
    /// RejectedDocument
    /// </summary>
    [DataContract(Name = "RejectedDocument")]
    public partial class RejectedDocument : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="RejectedDocument" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected RejectedDocument() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="RejectedDocument" /> class.
        /// </summary>
        /// <param name="codeNumber">codeNumber (required).</param>
        /// <param name="error">error (required).</param>
        public RejectedDocument(string codeNumber = default(string), GatewayError error = default(GatewayError))
        {
            // to ensure "codeNumber" is required (not null)
            if (codeNumber == null)
            {
                throw new ArgumentNullException("codeNumber is a required property for RejectedDocument and cannot be null");
            }
            this.CodeNumber = codeNumber;
            // to ensure "error" is required (not null)
            if (error == null)
            {
                throw new ArgumentNullException("error is a required property for RejectedDocument and cannot be null");
            }
            this.Error = error;
        }

        /// <summary>
        /// Gets or Sets CodeNumber
        /// </summary>
        [DataMember(Name = "codeNumber", IsRequired = true, EmitDefaultValue = true)]
        public string CodeNumber { get; set; }

        /// <summary>
        /// Gets or Sets Error
        /// </summary>
        [DataMember(Name = "error", IsRequired = true, EmitDefaultValue = true)]
        public GatewayError Error { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class RejectedDocument {\n");
            sb.Append("  CodeNumber: ").Append(CodeNumber).Append("\n");
            sb.Append("  Error: ").Append(Error).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
