/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MyInvois.Sdk.Client.OpenAPIDateConverter;

namespace MyInvois.Sdk.Model
{
    /// <summary>
    /// Phase where signing error occurred
    /// </summary>
    /// <value>Phase where signing error occurred</value>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum SigningErrorPhase
    {
        /// <summary>
        /// Enum Loading for value: loading
        /// </summary>
        [EnumMember(Value = "loading")]
        Loading = 1,

        /// <summary>
        /// Enum Signing for value: signing
        /// </summary>
        [EnumMember(Value = "signing")]
        Signing = 2,

        /// <summary>
        /// Enum Verification for value: verification
        /// </summary>
        [EnumMember(Value = "verification")]
        Verification = 3
    }

}
