/*
 * KLCubeLHDN MyInvois Middleware API
 *
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = MyInvois.Sdk.Client.OpenAPIDateConverter;

namespace MyInvois.Sdk.Model
{
    /// <summary>
    /// SubmitConsolidateRequest
    /// </summary>
    [DataContract(Name = "SubmitConsolidateRequest")]
    public partial class SubmitConsolidateRequest : IValidatableObject
    {
        /// <summary>
        /// Defines DocumentVersion
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DocumentVersionEnum
        {
            /// <summary>
            /// Enum _0 for value: 1.0
            /// </summary>
            [EnumMember(Value = "1.0")]
            _0 = 1,

            /// <summary>
            /// Enum _1 for value: 1.1
            /// </summary>
            [EnumMember(Value = "1.1")]
            _1 = 2
        }


        /// <summary>
        /// Gets or Sets DocumentVersion
        /// </summary>
        [DataMember(Name = "documentVersion", EmitDefaultValue = false)]
        public DocumentVersionEnum? DocumentVersion { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitConsolidateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubmitConsolidateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitConsolidateRequest" /> class.
        /// </summary>
        /// <param name="companyId">companyId (required).</param>
        /// <param name="documentVersion">documentVersion (default to DocumentVersionEnum._0).</param>
        /// <param name="buyerEmail">buyerEmail.</param>
        /// <param name="invoices">invoices (required).</param>
        public SubmitConsolidateRequest(string companyId = default(string), DocumentVersionEnum? documentVersion = DocumentVersionEnum._0, string buyerEmail = default(string), List<Invoice> invoices = default(List<Invoice>))
        {
            // to ensure "companyId" is required (not null)
            if (companyId == null)
            {
                throw new ArgumentNullException("companyId is a required property for SubmitConsolidateRequest and cannot be null");
            }
            this.CompanyId = companyId;
            // to ensure "invoices" is required (not null)
            if (invoices == null)
            {
                throw new ArgumentNullException("invoices is a required property for SubmitConsolidateRequest and cannot be null");
            }
            this.Invoices = invoices;
            this.DocumentVersion = documentVersion;
            this.BuyerEmail = buyerEmail;
        }

        /// <summary>
        /// Gets or Sets CompanyId
        /// </summary>
        [DataMember(Name = "companyId", IsRequired = true, EmitDefaultValue = true)]
        public string CompanyId { get; set; }

        /// <summary>
        /// Gets or Sets BuyerEmail
        /// </summary>
        [DataMember(Name = "buyerEmail", EmitDefaultValue = false)]
        public string BuyerEmail { get; set; }

        /// <summary>
        /// Gets or Sets Invoices
        /// </summary>
        [DataMember(Name = "invoices", IsRequired = true, EmitDefaultValue = true)]
        public List<Invoice> Invoices { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitConsolidateRequest {\n");
            sb.Append("  CompanyId: ").Append(CompanyId).Append("\n");
            sb.Append("  DocumentVersion: ").Append(DocumentVersion).Append("\n");
            sb.Append("  BuyerEmail: ").Append(BuyerEmail).Append("\n");
            sb.Append("  Invoices: ").Append(Invoices).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
