/* tslint:disable */
/* eslint-disable */
/**
 * KLCubeLHDN MyInvois Middleware API
 * API middleware gateway for Malaysia\'s MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Company
 */
export interface Company {
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'id'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'name'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'tin'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'idType'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'idValue'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'address'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'city'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'postalCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'phone'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'email'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof Company
     */
    'isActive'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'myinvoisEnv'?: CompanyMyinvoisEnvEnum;
    /**
     * 
     * @type {boolean}
     * @memberof Company
     */
    'hasCredentials'?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'createdAt'?: string;
    /**
     * 
     * @type {string}
     * @memberof Company
     */
    'updatedAt'?: string;
}

export const CompanyMyinvoisEnvEnum = {
    Sandbox: 'SANDBOX',
    Prod: 'PROD'
} as const;

export type CompanyMyinvoisEnvEnum = typeof CompanyMyinvoisEnvEnum[keyof typeof CompanyMyinvoisEnvEnum];


