/* tslint:disable */
/* eslint-disable */
/**
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia\'s MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Signing-related error codes. These are returned when document signing fails. 
 * @export
 * @enum {string}
 */

export const SigningErrorCode = {
    SigningDisabled: 'SIGNING_DISABLED',
    CertificateLoadFailed: 'CERTIFICATE_LOAD_FAILED',
    PrivateKeyLoadFailed: 'PRIVATE_KEY_LOAD_FAILED',
    CertificateExpired: 'CERTIFICATE_EXPIRED',
    CertificateNotYetValid: 'CERTIFICATE_NOT_YET_VALID',
    KeyCertificateMismatch: 'KEY_CERTIFICATE_MISMATCH',
    SigningFailed: 'SIGNING_FAILED',
    SignatureVerificationFailed: 'SIGNATURE_VERIFICATION_FAILED',
    InvalidDocumentVersion: 'INVALID_DOCUMENT_VERSION',
    SigningNotConfigured: 'SIGNING_NOT_CONFIGURED',
    SigningRequired: 'SIGNING_REQUIRED',
    DigestMismatch: 'DIGEST_MISMATCH',
    SignatureInvalid: 'SIGNATURE_INVALID',
    CertificateRejected: 'CERTIFICATE_REJECTED'
} as const;

export type SigningErrorCode = typeof SigningErrorCode[keyof typeof SigningErrorCode];



