/* tslint:disable */
/* eslint-disable */
/**
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia\'s MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SigningErrorCode } from './signing-error-code';
// May contain unused imports in some cases
// @ts-ignore
import type { SigningErrorPhase } from './signing-error-phase';

/**
 * Additional context for signing errors
 * @export
 * @interface SigningErrorContext
 */
export interface SigningErrorContext {
    /**
     * 
     * @type {SigningErrorCode}
     * @memberof SigningErrorContext
     */
    'code'?: SigningErrorCode;
    /**
     * 
     * @type {SigningErrorPhase}
     * @memberof SigningErrorContext
     */
    'phase'?: SigningErrorPhase;
    /**
     * Certificate subject (if available)
     * @type {string}
     * @memberof SigningErrorContext
     */
    'certificateSubject'?: string;
    /**
     * Document version being processed
     * @type {string}
     * @memberof SigningErrorContext
     */
    'documentVersion'?: string;
    /**
     * Document code number (if applicable)
     * @type {string}
     * @memberof SigningErrorContext
     */
    'documentCodeNumber'?: string;
}



