/* tslint:disable */
/* eslint-disable */
/**
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia\'s MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DocumentVersion } from './document-version';

/**
 * Signing subsystem health status
 * @export
 * @interface SigningHealthStatus
 */
export interface SigningHealthStatus {
    /**
     * Whether signing is enabled in configuration
     * @type {boolean}
     * @memberof SigningHealthStatus
     */
    'enabled'?: boolean;
    /**
     * Whether the certificate is currently valid
     * @type {boolean}
     * @memberof SigningHealthStatus
     */
    'certificateValid'?: boolean;
    /**
     * Certificate expiration date (ISO 8601)
     * @type {string}
     * @memberof SigningHealthStatus
     */
    'certificateExpiry'?: string;
    /**
     * Certificate subject name
     * @type {string}
     * @memberof SigningHealthStatus
     */
    'certificateSubject'?: string;
    /**
     * 
     * @type {DocumentVersion}
     * @memberof SigningHealthStatus
     */
    'defaultVersion'?: DocumentVersion;
    /**
     * Warning flag if certificate expires within 30 days
     * @type {boolean}
     * @memberof SigningHealthStatus
     */
    'expiringWithin30Days'?: boolean;
}



