/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.myinvois.sdk.ApiClient;
/**
 * DocumentInput
 */
@JsonPropertyOrder({
  DocumentInput.JSON_PROPERTY_FORMAT,
  DocumentInput.JSON_PROPERTY_CODE_NUMBER,
  DocumentInput.JSON_PROPERTY_RAW_DOCUMENT,
  DocumentInput.JSON_PROPERTY_DOCUMENT_BASE64,
  DocumentInput.JSON_PROPERTY_DOCUMENT_HASH_SHA256
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class DocumentInput {
  /**
   * Document format
   */
  public enum FormatEnum {
    XML(String.valueOf("XML")),
    
    JSON(String.valueOf("JSON"));

    private String value;

    FormatEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static FormatEnum fromValue(String value) {
      for (FormatEnum b : FormatEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_FORMAT = "format";
  @jakarta.annotation.Nonnull
  private FormatEnum format;

  public static final String JSON_PROPERTY_CODE_NUMBER = "codeNumber";
  @jakarta.annotation.Nonnull
  private String codeNumber;

  public static final String JSON_PROPERTY_RAW_DOCUMENT = "rawDocument";
  @jakarta.annotation.Nullable
  private String rawDocument;

  public static final String JSON_PROPERTY_DOCUMENT_BASE64 = "documentBase64";
  @jakarta.annotation.Nullable
  private byte[] documentBase64;

  public static final String JSON_PROPERTY_DOCUMENT_HASH_SHA256 = "documentHashSha256";
  @jakarta.annotation.Nullable
  private String documentHashSha256;

  public DocumentInput() { 
  }

  public DocumentInput format(@jakarta.annotation.Nonnull FormatEnum format) {
    this.format = format;
    return this;
  }

  /**
   * Document format
   * @return format
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public FormatEnum getFormat() {
    return format;
  }


  @JsonProperty(JSON_PROPERTY_FORMAT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFormat(@jakarta.annotation.Nonnull FormatEnum format) {
    this.format = format;
  }


  public DocumentInput codeNumber(@jakarta.annotation.Nonnull String codeNumber) {
    this.codeNumber = codeNumber;
    return this;
  }

  /**
   * Invoice/document code number
   * @return codeNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCodeNumber() {
    return codeNumber;
  }


  @JsonProperty(JSON_PROPERTY_CODE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodeNumber(@jakarta.annotation.Nonnull String codeNumber) {
    this.codeNumber = codeNumber;
  }


  public DocumentInput rawDocument(@jakarta.annotation.Nullable String rawDocument) {
    this.rawDocument = rawDocument;
    return this;
  }

  /**
   * Raw document content (gateway will base64 encode and hash)
   * @return rawDocument
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RAW_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRawDocument() {
    return rawDocument;
  }


  @JsonProperty(JSON_PROPERTY_RAW_DOCUMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRawDocument(@jakarta.annotation.Nullable String rawDocument) {
    this.rawDocument = rawDocument;
  }


  public DocumentInput documentBase64(@jakarta.annotation.Nullable byte[] documentBase64) {
    this.documentBase64 = documentBase64;
    return this;
  }

  /**
   * Pre-encoded base64 document
   * @return documentBase64
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public byte[] getDocumentBase64() {
    return documentBase64;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_BASE64)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentBase64(@jakarta.annotation.Nullable byte[] documentBase64) {
    this.documentBase64 = documentBase64;
  }


  public DocumentInput documentHashSha256(@jakarta.annotation.Nullable String documentHashSha256) {
    this.documentHashSha256 = documentHashSha256;
    return this;
  }

  /**
   * Pre-computed SHA256 hash
   * @return documentHashSha256
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_HASH_SHA256)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDocumentHashSha256() {
    return documentHashSha256;
  }


  @JsonProperty(JSON_PROPERTY_DOCUMENT_HASH_SHA256)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentHashSha256(@jakarta.annotation.Nullable String documentHashSha256) {
    this.documentHashSha256 = documentHashSha256;
  }


  /**
   * Return true if this DocumentInput object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentInput documentInput = (DocumentInput) o;
    return Objects.equals(this.format, documentInput.format) &&
        Objects.equals(this.codeNumber, documentInput.codeNumber) &&
        Objects.equals(this.rawDocument, documentInput.rawDocument) &&
        Arrays.equals(this.documentBase64, documentInput.documentBase64) &&
        Objects.equals(this.documentHashSha256, documentInput.documentHashSha256);
  }

  @Override
  public int hashCode() {
    return Objects.hash(format, codeNumber, rawDocument, Arrays.hashCode(documentBase64), documentHashSha256);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentInput {\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    codeNumber: ").append(toIndentedString(codeNumber)).append("\n");
    sb.append("    rawDocument: ").append(toIndentedString(rawDocument)).append("\n");
    sb.append("    documentBase64: ").append(toIndentedString(documentBase64)).append("\n");
    sb.append("    documentHashSha256: ").append(toIndentedString(documentHashSha256)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `format` to the URL query string
    if (getFormat() != null) {
      joiner.add(String.format("%sformat%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getFormat()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `codeNumber` to the URL query string
    if (getCodeNumber() != null) {
      joiner.add(String.format("%scodeNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `rawDocument` to the URL query string
    if (getRawDocument() != null) {
      joiner.add(String.format("%srawDocument%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRawDocument()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `documentBase64` to the URL query string
    if (getDocumentBase64() != null) {
      joiner.add(String.format("%sdocumentBase64%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDocumentBase64()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `documentHashSha256` to the URL query string
    if (getDocumentHashSha256() != null) {
      joiner.add(String.format("%sdocumentHashSha256%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDocumentHashSha256()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

