/*
 * HashLHDN MyInvois Middleware API
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Client:** Hashmato | **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.myinvois.sdk.ApiClient;
/**
 * ReadinessResponseChecks
 */
@JsonPropertyOrder({
  ReadinessResponseChecks.JSON_PROPERTY_DATABASE,
  ReadinessResponseChecks.JSON_PROPERTY_REDIS
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ReadinessResponseChecks {
  /**
   * Gets or Sets database
   */
  public enum DatabaseEnum {
    OK(String.valueOf("ok")),
    
    ERROR(String.valueOf("error"));

    private String value;

    DatabaseEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static DatabaseEnum fromValue(String value) {
      for (DatabaseEnum b : DatabaseEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_DATABASE = "database";
  @jakarta.annotation.Nullable
  private DatabaseEnum database;

  /**
   * Gets or Sets redis
   */
  public enum RedisEnum {
    OK(String.valueOf("ok")),
    
    ERROR(String.valueOf("error"));

    private String value;

    RedisEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static RedisEnum fromValue(String value) {
      for (RedisEnum b : RedisEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  public static final String JSON_PROPERTY_REDIS = "redis";
  @jakarta.annotation.Nullable
  private RedisEnum redis;

  public ReadinessResponseChecks() { 
  }

  public ReadinessResponseChecks database(@jakarta.annotation.Nullable DatabaseEnum database) {
    this.database = database;
    return this;
  }

  /**
   * Get database
   * @return database
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DATABASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public DatabaseEnum getDatabase() {
    return database;
  }


  @JsonProperty(JSON_PROPERTY_DATABASE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDatabase(@jakarta.annotation.Nullable DatabaseEnum database) {
    this.database = database;
  }


  public ReadinessResponseChecks redis(@jakarta.annotation.Nullable RedisEnum redis) {
    this.redis = redis;
    return this;
  }

  /**
   * Get redis
   * @return redis
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_REDIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public RedisEnum getRedis() {
    return redis;
  }


  @JsonProperty(JSON_PROPERTY_REDIS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRedis(@jakarta.annotation.Nullable RedisEnum redis) {
    this.redis = redis;
  }


  /**
   * Return true if this ReadinessResponse_checks object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReadinessResponseChecks readinessResponseChecks = (ReadinessResponseChecks) o;
    return Objects.equals(this.database, readinessResponseChecks.database) &&
        Objects.equals(this.redis, readinessResponseChecks.redis);
  }

  @Override
  public int hashCode() {
    return Objects.hash(database, redis);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReadinessResponseChecks {\n");
    sb.append("    database: ").append(toIndentedString(database)).append("\n");
    sb.append("    redis: ").append(toIndentedString(redis)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `database` to the URL query string
    if (getDatabase() != null) {
      joiner.add(String.format("%sdatabase%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getDatabase()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `redis` to the URL query string
    if (getRedis() != null) {
      joiner.add(String.format("%sredis%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getRedis()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

