/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.myinvois.sdk.model.GatewayError;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.myinvois.sdk.ApiClient;
/**
 * RejectedDocument
 */
@JsonPropertyOrder({
  RejectedDocument.JSON_PROPERTY_CODE_NUMBER,
  RejectedDocument.JSON_PROPERTY_ERROR
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class RejectedDocument {
  public static final String JSON_PROPERTY_CODE_NUMBER = "codeNumber";
  @jakarta.annotation.Nonnull
  private String codeNumber;

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nonnull
  private GatewayError error;

  public RejectedDocument() { 
  }

  public RejectedDocument codeNumber(@jakarta.annotation.Nonnull String codeNumber) {
    this.codeNumber = codeNumber;
    return this;
  }

  /**
   * Get codeNumber
   * @return codeNumber
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_CODE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCodeNumber() {
    return codeNumber;
  }


  @JsonProperty(JSON_PROPERTY_CODE_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCodeNumber(@jakarta.annotation.Nonnull String codeNumber) {
    this.codeNumber = codeNumber;
  }


  public RejectedDocument error(@jakarta.annotation.Nonnull GatewayError error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @jakarta.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public GatewayError getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setError(@jakarta.annotation.Nonnull GatewayError error) {
    this.error = error;
  }


  /**
   * Return true if this RejectedDocument object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RejectedDocument rejectedDocument = (RejectedDocument) o;
    return Objects.equals(this.codeNumber, rejectedDocument.codeNumber) &&
        Objects.equals(this.error, rejectedDocument.error);
  }

  @Override
  public int hashCode() {
    return Objects.hash(codeNumber, error);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RejectedDocument {\n");
    sb.append("    codeNumber: ").append(toIndentedString(codeNumber)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `codeNumber` to the URL query string
    if (getCodeNumber() != null) {
      joiner.add(String.format("%scodeNumber%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getCodeNumber()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(getError().toUrlQueryString(prefix + "error" + suffix));
    }

    return joiner.toString();
  }
}

