/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.myinvois.sdk.model.DocumentVersion;
import com.myinvois.sdk.model.Environment;
import com.myinvois.sdk.model.SessionCreateIntermediary;
import com.myinvois.sdk.model.SessionCreateTaxpayer;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import com.fasterxml.jackson.core.type.TypeReference;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.JsonToken;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.MapperFeature;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.myinvois.sdk.JSON;

@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
@JsonDeserialize(using = SessionCreateRequest.SessionCreateRequestDeserializer.class)
@JsonSerialize(using = SessionCreateRequest.SessionCreateRequestSerializer.class)
public class SessionCreateRequest extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(SessionCreateRequest.class.getName());

    public static class SessionCreateRequestSerializer extends StdSerializer<SessionCreateRequest> {
        public SessionCreateRequestSerializer(Class<SessionCreateRequest> t) {
            super(t);
        }

        public SessionCreateRequestSerializer() {
            this(null);
        }

        @Override
        public void serialize(SessionCreateRequest value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class SessionCreateRequestDeserializer extends StdDeserializer<SessionCreateRequest> {
        public SessionCreateRequestDeserializer() {
            this(SessionCreateRequest.class);
        }

        public SessionCreateRequestDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public SessionCreateRequest deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();
            Object deserialized = null;
            boolean typeCoercion = ctxt.isEnabled(MapperFeature.ALLOW_COERCION_OF_SCALARS);
            int match = 0;
            JsonToken token = tree.traverse(jp.getCodec()).nextToken();
            // deserialize SessionCreateIntermediary
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SessionCreateIntermediary.class.equals(Integer.class) || SessionCreateIntermediary.class.equals(Long.class) || SessionCreateIntermediary.class.equals(Float.class) || SessionCreateIntermediary.class.equals(Double.class) || SessionCreateIntermediary.class.equals(Boolean.class) || SessionCreateIntermediary.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SessionCreateIntermediary.class.equals(Integer.class) || SessionCreateIntermediary.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SessionCreateIntermediary.class.equals(Float.class) || SessionCreateIntermediary.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SessionCreateIntermediary.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SessionCreateIntermediary.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SessionCreateIntermediary.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SessionCreateIntermediary'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SessionCreateIntermediary'", e);
            }

            // deserialize SessionCreateTaxpayer
            try {
                boolean attemptParsing = true;
                // ensure that we respect type coercion as set on the client ObjectMapper
                if (SessionCreateTaxpayer.class.equals(Integer.class) || SessionCreateTaxpayer.class.equals(Long.class) || SessionCreateTaxpayer.class.equals(Float.class) || SessionCreateTaxpayer.class.equals(Double.class) || SessionCreateTaxpayer.class.equals(Boolean.class) || SessionCreateTaxpayer.class.equals(String.class)) {
                    attemptParsing = typeCoercion;
                    if (!attemptParsing) {
                        attemptParsing |= ((SessionCreateTaxpayer.class.equals(Integer.class) || SessionCreateTaxpayer.class.equals(Long.class)) && token == JsonToken.VALUE_NUMBER_INT);
                        attemptParsing |= ((SessionCreateTaxpayer.class.equals(Float.class) || SessionCreateTaxpayer.class.equals(Double.class)) && token == JsonToken.VALUE_NUMBER_FLOAT);
                        attemptParsing |= (SessionCreateTaxpayer.class.equals(Boolean.class) && (token == JsonToken.VALUE_FALSE || token == JsonToken.VALUE_TRUE));
                        attemptParsing |= (SessionCreateTaxpayer.class.equals(String.class) && token == JsonToken.VALUE_STRING);
                    }
                }
                if (attemptParsing) {
                    deserialized = tree.traverse(jp.getCodec()).readValueAs(SessionCreateTaxpayer.class);
                    // TODO: there is no validation against JSON schema constraints
                    // (min, max, enum, pattern...), this does not perform a strict JSON
                    // validation, which means the 'match' count may be higher than it should be.
                    match++;
                    log.log(Level.FINER, "Input data matches schema 'SessionCreateTaxpayer'");
                }
            } catch (Exception e) {
                // deserialization failed, continue
                log.log(Level.FINER, "Input data does not match schema 'SessionCreateTaxpayer'", e);
            }

            if (match == 1) {
                SessionCreateRequest ret = new SessionCreateRequest();
                ret.setActualInstance(deserialized);
                return ret;
            }
            throw new IOException(String.format("Failed deserialization for SessionCreateRequest: %d classes match result, expected 1", match));
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public SessionCreateRequest getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "SessionCreateRequest cannot be null");
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<>();

    public SessionCreateRequest() {
        super("oneOf", Boolean.FALSE);
    }

    public SessionCreateRequest(SessionCreateIntermediary o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public SessionCreateRequest(SessionCreateTaxpayer o) {
        super("oneOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("SessionCreateIntermediary", SessionCreateIntermediary.class);
        schemas.put("SessionCreateTaxpayer", SessionCreateTaxpayer.class);
        JSON.registerDescendants(SessionCreateRequest.class, Collections.unmodifiableMap(schemas));
        // Initialize and register the discriminator mappings.
        Map<String, Class<?>> mappings = new HashMap<String, Class<?>>();
        mappings.put("INTERMEDIARY", SessionCreateIntermediary.class);
        mappings.put("TAXPAYER", SessionCreateTaxpayer.class);
        mappings.put("SessionCreateIntermediary", SessionCreateIntermediary.class);
        mappings.put("SessionCreateTaxpayer", SessionCreateTaxpayer.class);
        mappings.put("SessionCreateRequest", SessionCreateRequest.class);
        JSON.registerDiscriminator(SessionCreateRequest.class, "mode", mappings);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return SessionCreateRequest.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * SessionCreateIntermediary, SessionCreateTaxpayer
     *
     * It could be an instance of the 'oneOf' schemas.
     * The oneOf child schemas may themselves be a composed schema (allOf, anyOf, oneOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(SessionCreateIntermediary.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(SessionCreateTaxpayer.class, instance, new HashSet<Class<?>>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be SessionCreateIntermediary, SessionCreateTaxpayer");
    }

    /**
     * Get the actual instance, which can be the following:
     * SessionCreateIntermediary, SessionCreateTaxpayer
     *
     * @return The actual instance (SessionCreateIntermediary, SessionCreateTaxpayer)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `SessionCreateIntermediary`. If the actual instance is not `SessionCreateIntermediary`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SessionCreateIntermediary`
     * @throws ClassCastException if the instance is not `SessionCreateIntermediary`
     */
    public SessionCreateIntermediary getSessionCreateIntermediary() throws ClassCastException {
        return (SessionCreateIntermediary)super.getActualInstance();
    }

    /**
     * Get the actual instance of `SessionCreateTaxpayer`. If the actual instance is not `SessionCreateTaxpayer`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `SessionCreateTaxpayer`
     * @throws ClassCastException if the instance is not `SessionCreateTaxpayer`
     */
    public SessionCreateTaxpayer getSessionCreateTaxpayer() throws ClassCastException {
        return (SessionCreateTaxpayer)super.getActualInstance();
    }



  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    if (getActualInstance() instanceof SessionCreateTaxpayer) {
        if (getActualInstance() != null) {
          joiner.add(((SessionCreateTaxpayer)getActualInstance()).toUrlQueryString(prefix + "one_of_0" + suffix));
        }
        return joiner.toString();
    }
    if (getActualInstance() instanceof SessionCreateIntermediary) {
        if (getActualInstance() != null) {
          joiner.add(((SessionCreateIntermediary)getActualInstance()).toUrlQueryString(prefix + "one_of_1" + suffix));
        }
        return joiner.toString();
    }
    return null;
  }

}

