/*
 * MyInvois Middleware Gateway
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.myinvois.sdk.model;

import java.net.URLEncoder;
import java.nio.charset.StandardCharsets;
import java.util.StringJoiner;
import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;


import com.myinvois.sdk.ApiClient;
/**
 * ValidationError
 */
@JsonPropertyOrder({
  ValidationError.JSON_PROPERTY_PROPERTY_NAME,
  ValidationError.JSON_PROPERTY_PROPERTY_PATH,
  ValidationError.JSON_PROPERTY_ERROR_CODE,
  ValidationError.JSON_PROPERTY_ERROR,
  ValidationError.JSON_PROPERTY_ERROR_M_S
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.10.0")
public class ValidationError {
  public static final String JSON_PROPERTY_PROPERTY_NAME = "propertyName";
  @jakarta.annotation.Nullable
  private String propertyName;

  public static final String JSON_PROPERTY_PROPERTY_PATH = "propertyPath";
  @jakarta.annotation.Nullable
  private String propertyPath;

  public static final String JSON_PROPERTY_ERROR_CODE = "errorCode";
  @jakarta.annotation.Nullable
  private String errorCode;

  public static final String JSON_PROPERTY_ERROR = "error";
  @jakarta.annotation.Nullable
  private String error;

  public static final String JSON_PROPERTY_ERROR_M_S = "errorMS";
  @jakarta.annotation.Nullable
  private String errorMS;

  public ValidationError() { 
  }

  public ValidationError propertyName(@jakarta.annotation.Nullable String propertyName) {
    this.propertyName = propertyName;
    return this;
  }

  /**
   * Get propertyName
   * @return propertyName
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPropertyName() {
    return propertyName;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyName(@jakarta.annotation.Nullable String propertyName) {
    this.propertyName = propertyName;
  }


  public ValidationError propertyPath(@jakarta.annotation.Nullable String propertyPath) {
    this.propertyPath = propertyPath;
    return this;
  }

  /**
   * Get propertyPath
   * @return propertyPath
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PROPERTY_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPropertyPath() {
    return propertyPath;
  }


  @JsonProperty(JSON_PROPERTY_PROPERTY_PATH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPropertyPath(@jakarta.annotation.Nullable String propertyPath) {
    this.propertyPath = propertyPath;
  }


  public ValidationError errorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
    return this;
  }

  /**
   * Get errorCode
   * @return errorCode
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorCode() {
    return errorCode;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorCode(@jakarta.annotation.Nullable String errorCode) {
    this.errorCode = errorCode;
  }


  public ValidationError error(@jakarta.annotation.Nullable String error) {
    this.error = error;
    return this;
  }

  /**
   * Get error
   * @return error
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getError() {
    return error;
  }


  @JsonProperty(JSON_PROPERTY_ERROR)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setError(@jakarta.annotation.Nullable String error) {
    this.error = error;
  }


  public ValidationError errorMS(@jakarta.annotation.Nullable String errorMS) {
    this.errorMS = errorMS;
    return this;
  }

  /**
   * Get errorMS
   * @return errorMS
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ERROR_M_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getErrorMS() {
    return errorMS;
  }


  @JsonProperty(JSON_PROPERTY_ERROR_M_S)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setErrorMS(@jakarta.annotation.Nullable String errorMS) {
    this.errorMS = errorMS;
  }


  /**
   * Return true if this ValidationError object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ValidationError validationError = (ValidationError) o;
    return Objects.equals(this.propertyName, validationError.propertyName) &&
        Objects.equals(this.propertyPath, validationError.propertyPath) &&
        Objects.equals(this.errorCode, validationError.errorCode) &&
        Objects.equals(this.error, validationError.error) &&
        Objects.equals(this.errorMS, validationError.errorMS);
  }

  @Override
  public int hashCode() {
    return Objects.hash(propertyName, propertyPath, errorCode, error, errorMS);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ValidationError {\n");
    sb.append("    propertyName: ").append(toIndentedString(propertyName)).append("\n");
    sb.append("    propertyPath: ").append(toIndentedString(propertyPath)).append("\n");
    sb.append("    errorCode: ").append(toIndentedString(errorCode)).append("\n");
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    errorMS: ").append(toIndentedString(errorMS)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `propertyName` to the URL query string
    if (getPropertyName() != null) {
      joiner.add(String.format("%spropertyName%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPropertyName()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `propertyPath` to the URL query string
    if (getPropertyPath() != null) {
      joiner.add(String.format("%spropertyPath%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getPropertyPath()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `errorCode` to the URL query string
    if (getErrorCode() != null) {
      joiner.add(String.format("%serrorCode%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getErrorCode()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `error` to the URL query string
    if (getError() != null) {
      joiner.add(String.format("%serror%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getError()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    // add `errorMS` to the URL query string
    if (getErrorMS() != null) {
      joiner.add(String.format("%serrorMS%s=%s", prefix, suffix, URLEncoder.encode(ApiClient.valueToString(getErrorMS()), StandardCharsets.UTF_8).replaceAll("\\+", "%20")));
    }

    return joiner.toString();
  }
}

