/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentDetails
        //private DocumentDetails instance;

        public DocumentDetailsTests()
        {
            // TODO uncomment below to create an instance of DocumentDetails
            //instance = new DocumentDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentDetails
        /// </summary>
        [Fact]
        public void DocumentDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentDetails
            //Assert.IsType<DocumentDetails>(instance);
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'LongId'
        /// </summary>
        [Fact]
        public void LongIdTest()
        {
            // TODO unit test for the property 'LongId'
        }

        /// <summary>
        /// Test the property 'InternalId'
        /// </summary>
        [Fact]
        public void InternalIdTest()
        {
            // TODO unit test for the property 'InternalId'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'DateTimeIssued'
        /// </summary>
        [Fact]
        public void DateTimeIssuedTest()
        {
            // TODO unit test for the property 'DateTimeIssued'
        }

        /// <summary>
        /// Test the property 'DateTimeReceived'
        /// </summary>
        [Fact]
        public void DateTimeReceivedTest()
        {
            // TODO unit test for the property 'DateTimeReceived'
        }

        /// <summary>
        /// Test the property 'DateTimeValidated'
        /// </summary>
        [Fact]
        public void DateTimeValidatedTest()
        {
            // TODO unit test for the property 'DateTimeValidated'
        }

        /// <summary>
        /// Test the property 'ValidationErrors'
        /// </summary>
        [Fact]
        public void ValidationErrorsTest()
        {
            // TODO unit test for the property 'ValidationErrors'
        }
    }
}
