/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentListItem
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentListItemTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentListItem
        //private DocumentListItem instance;

        public DocumentListItemTests()
        {
            // TODO uncomment below to create an instance of DocumentListItem
            //instance = new DocumentListItem();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentListItem
        /// </summary>
        [Fact]
        public void DocumentListItemInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentListItem
            //Assert.IsType<DocumentListItem>(instance);
        }

        /// <summary>
        /// Test the property 'Uuid'
        /// </summary>
        [Fact]
        public void UuidTest()
        {
            // TODO unit test for the property 'Uuid'
        }

        /// <summary>
        /// Test the property 'SubmissionUid'
        /// </summary>
        [Fact]
        public void SubmissionUidTest()
        {
            // TODO unit test for the property 'SubmissionUid'
        }

        /// <summary>
        /// Test the property 'LongId'
        /// </summary>
        [Fact]
        public void LongIdTest()
        {
            // TODO unit test for the property 'LongId'
        }

        /// <summary>
        /// Test the property 'InternalId'
        /// </summary>
        [Fact]
        public void InternalIdTest()
        {
            // TODO unit test for the property 'InternalId'
        }

        /// <summary>
        /// Test the property 'TypeName'
        /// </summary>
        [Fact]
        public void TypeNameTest()
        {
            // TODO unit test for the property 'TypeName'
        }

        /// <summary>
        /// Test the property 'TypeVersionName'
        /// </summary>
        [Fact]
        public void TypeVersionNameTest()
        {
            // TODO unit test for the property 'TypeVersionName'
        }

        /// <summary>
        /// Test the property 'IssuerTin'
        /// </summary>
        [Fact]
        public void IssuerTinTest()
        {
            // TODO unit test for the property 'IssuerTin'
        }

        /// <summary>
        /// Test the property 'IssuerName'
        /// </summary>
        [Fact]
        public void IssuerNameTest()
        {
            // TODO unit test for the property 'IssuerName'
        }

        /// <summary>
        /// Test the property 'ReceiverId'
        /// </summary>
        [Fact]
        public void ReceiverIdTest()
        {
            // TODO unit test for the property 'ReceiverId'
        }

        /// <summary>
        /// Test the property 'ReceiverName'
        /// </summary>
        [Fact]
        public void ReceiverNameTest()
        {
            // TODO unit test for the property 'ReceiverName'
        }

        /// <summary>
        /// Test the property 'DateTimeIssued'
        /// </summary>
        [Fact]
        public void DateTimeIssuedTest()
        {
            // TODO unit test for the property 'DateTimeIssued'
        }

        /// <summary>
        /// Test the property 'DateTimeReceived'
        /// </summary>
        [Fact]
        public void DateTimeReceivedTest()
        {
            // TODO unit test for the property 'DateTimeReceived'
        }

        /// <summary>
        /// Test the property 'DateTimeValidated'
        /// </summary>
        [Fact]
        public void DateTimeValidatedTest()
        {
            // TODO unit test for the property 'DateTimeValidated'
        }

        /// <summary>
        /// Test the property 'TotalPayableAmount'
        /// </summary>
        [Fact]
        public void TotalPayableAmountTest()
        {
            // TODO unit test for the property 'TotalPayableAmount'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'CancelDateTime'
        /// </summary>
        [Fact]
        public void CancelDateTimeTest()
        {
            // TODO unit test for the property 'CancelDateTime'
        }

        /// <summary>
        /// Test the property 'RejectDateTime'
        /// </summary>
        [Fact]
        public void RejectDateTimeTest()
        {
            // TODO unit test for the property 'RejectDateTime'
        }
    }
}
