/*
 * HashLHDN MyInvois Middleware API
 *
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Client:** Hashmato | **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceDetailsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceDetails
        //private InvoiceDetails instance;

        public InvoiceDetailsTests()
        {
            // TODO uncomment below to create an instance of InvoiceDetails
            //instance = new InvoiceDetails();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceDetails
        /// </summary>
        [Fact]
        public void InvoiceDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceDetails
            //Assert.IsType<InvoiceDetails>(instance);
        }

        /// <summary>
        /// Test the property 'TrackingId'
        /// </summary>
        [Fact]
        public void TrackingIdTest()
        {
            // TODO unit test for the property 'TrackingId'
        }

        /// <summary>
        /// Test the property 'InvoiceNumber'
        /// </summary>
        [Fact]
        public void InvoiceNumberTest()
        {
            // TODO unit test for the property 'InvoiceNumber'
        }

        /// <summary>
        /// Test the property 'InvoiceDate'
        /// </summary>
        [Fact]
        public void InvoiceDateTest()
        {
            // TODO unit test for the property 'InvoiceDate'
        }

        /// <summary>
        /// Test the property 'InvoiceType'
        /// </summary>
        [Fact]
        public void InvoiceTypeTest()
        {
            // TODO unit test for the property 'InvoiceType'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'MyinvoisUuid'
        /// </summary>
        [Fact]
        public void MyinvoisUuidTest()
        {
            // TODO unit test for the property 'MyinvoisUuid'
        }

        /// <summary>
        /// Test the property 'MyinvoisLongId'
        /// </summary>
        [Fact]
        public void MyinvoisLongIdTest()
        {
            // TODO unit test for the property 'MyinvoisLongId'
        }

        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

        /// <summary>
        /// Test the property 'Discount'
        /// </summary>
        [Fact]
        public void DiscountTest()
        {
            // TODO unit test for the property 'Discount'
        }

        /// <summary>
        /// Test the property 'Rounding'
        /// </summary>
        [Fact]
        public void RoundingTest()
        {
            // TODO unit test for the property 'Rounding'
        }

        /// <summary>
        /// Test the property 'TaxAmount'
        /// </summary>
        [Fact]
        public void TaxAmountTest()
        {
            // TODO unit test for the property 'TaxAmount'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }

        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
