/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing Mode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ModeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Mode
        //private Mode instance;

        public ModeTests()
        {
            // TODO uncomment below to create an instance of Mode
            //instance = new Mode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Mode
        /// </summary>
        [Fact]
        public void ModeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Mode
            //Assert.IsType<Mode>(instance);
        }
    }
}
