/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SigningHealthStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SigningHealthStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SigningHealthStatus
        //private SigningHealthStatus instance;

        public SigningHealthStatusTests()
        {
            // TODO uncomment below to create an instance of SigningHealthStatus
            //instance = new SigningHealthStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SigningHealthStatus
        /// </summary>
        [Fact]
        public void SigningHealthStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" SigningHealthStatus
            //Assert.IsType<SigningHealthStatus>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'CertificateValid'
        /// </summary>
        [Fact]
        public void CertificateValidTest()
        {
            // TODO unit test for the property 'CertificateValid'
        }

        /// <summary>
        /// Test the property 'CertificateExpiry'
        /// </summary>
        [Fact]
        public void CertificateExpiryTest()
        {
            // TODO unit test for the property 'CertificateExpiry'
        }

        /// <summary>
        /// Test the property 'CertificateSubject'
        /// </summary>
        [Fact]
        public void CertificateSubjectTest()
        {
            // TODO unit test for the property 'CertificateSubject'
        }

        /// <summary>
        /// Test the property 'DefaultVersion'
        /// </summary>
        [Fact]
        public void DefaultVersionTest()
        {
            // TODO unit test for the property 'DefaultVersion'
        }

        /// <summary>
        /// Test the property 'ExpiringWithin30Days'
        /// </summary>
        [Fact]
        public void ExpiringWithin30DaysTest()
        {
            // TODO unit test for the property 'ExpiringWithin30Days'
        }
    }
}
