/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SigningErrorCode
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SigningErrorCodeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SigningErrorCode
        //private SigningErrorCode instance;

        public SigningErrorCodeTests()
        {
            // TODO uncomment below to create an instance of SigningErrorCode
            //instance = new SigningErrorCode();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SigningErrorCode
        /// </summary>
        [Fact]
        public void SigningErrorCodeInstanceTest()
        {
            // TODO uncomment below to test "IsType" SigningErrorCode
            //Assert.IsType<SigningErrorCode>(instance);
        }
    }
}
