/*
 * KLCubeLHDN MyInvois Middleware API
 *
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing SubmitConsolidateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SubmitConsolidateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SubmitConsolidateRequest
        //private SubmitConsolidateRequest instance;

        public SubmitConsolidateRequestTests()
        {
            // TODO uncomment below to create an instance of SubmitConsolidateRequest
            //instance = new SubmitConsolidateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SubmitConsolidateRequest
        /// </summary>
        [Fact]
        public void SubmitConsolidateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" SubmitConsolidateRequest
            //Assert.IsType<SubmitConsolidateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'CompanyId'
        /// </summary>
        [Fact]
        public void CompanyIdTest()
        {
            // TODO unit test for the property 'CompanyId'
        }

        /// <summary>
        /// Test the property 'DocumentVersion'
        /// </summary>
        [Fact]
        public void DocumentVersionTest()
        {
            // TODO unit test for the property 'DocumentVersion'
        }

        /// <summary>
        /// Test the property 'BuyerEmail'
        /// </summary>
        [Fact]
        public void BuyerEmailTest()
        {
            // TODO unit test for the property 'BuyerEmail'
        }

        /// <summary>
        /// Test the property 'Invoices'
        /// </summary>
        [Fact]
        public void InvoicesTest()
        {
            // TODO unit test for the property 'Invoices'
        }
    }
}
