/*
 * HashLHDN MyInvois Middleware API
 *
 * API middleware gateway for Malaysia's MyInvois e-invoicing system (LHDN).  **Client:** Hashmato | **Version:** 1.1.1  ## Features - 4 Submission Endpoints (Consolidate, JustSave, Buyer, Personal) - JWT Authentication with Access & Refresh Tokens - User/Role/Company Management - Document Operations (List, Status, PDF, Cancel) - Digital Signing v1.1 (XAdES signatures) - Background Status Polling  ## Authentication All endpoints except `/api/v1/auth/login` require JWT authentication. Include the access token in the Authorization header: ``` Authorization: Bearer <access_token> ``` 
 *
 * The version of the OpenAPI document: 1.1.1
 * Contact: hello@zahidaramai.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using MyInvois.Sdk.Model;
using MyInvois.Sdk.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace MyInvois.Sdk.Test.Model
{
    /// <summary>
    ///  Class for testing UpdateCompanyRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UpdateCompanyRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UpdateCompanyRequest
        //private UpdateCompanyRequest instance;

        public UpdateCompanyRequestTests()
        {
            // TODO uncomment below to create an instance of UpdateCompanyRequest
            //instance = new UpdateCompanyRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UpdateCompanyRequest
        /// </summary>
        [Fact]
        public void UpdateCompanyRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" UpdateCompanyRequest
            //Assert.IsType<UpdateCompanyRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

        /// <summary>
        /// Test the property 'City'
        /// </summary>
        [Fact]
        public void CityTest()
        {
            // TODO unit test for the property 'City'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'PostalCode'
        /// </summary>
        [Fact]
        public void PostalCodeTest()
        {
            // TODO unit test for the property 'PostalCode'
        }

        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Fact]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'IsActive'
        /// </summary>
        [Fact]
        public void IsActiveTest()
        {
            // TODO unit test for the property 'IsActive'
        }

        /// <summary>
        /// Test the property 'MyinvoisEnv'
        /// </summary>
        [Fact]
        public void MyinvoisEnvTest()
        {
            // TODO unit test for the property 'MyinvoisEnv'
        }
    }
}
