/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MyInvois.Sdk.Client;
using MyInvois.Sdk.Api;
// uncomment below to import models
//using MyInvois.Sdk.Model;

namespace MyInvois.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing DocumentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class DocumentsApiTests : IDisposable
    {
        private DocumentsApi instance;

        public DocumentsApiTests()
        {
            instance = new DocumentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' DocumentsApi
            //Assert.IsType<DocumentsApi>(instance);
        }

        /// <summary>
        /// Test CancelDocument
        /// </summary>
        [Fact]
        public void CancelDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //DocumentStateChangeRequest documentStateChangeRequest = null;
            //var response = instance.CancelDocument(uuid, documentStateChangeRequest);
            //Assert.IsType<DocumentStateChangeResponse>(response);
        }

        /// <summary>
        /// Test GetDocumentDetails
        /// </summary>
        [Fact]
        public void GetDocumentDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //string sessionId = null;
            //var response = instance.GetDocumentDetails(uuid, sessionId);
            //Assert.IsType<DocumentDetails>(response);
        }

        /// <summary>
        /// Test RejectDocument
        /// </summary>
        [Fact]
        public void RejectDocumentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid uuid = null;
            //DocumentStateChangeRequest documentStateChangeRequest = null;
            //var response = instance.RejectDocument(uuid, documentStateChangeRequest);
            //Assert.IsType<DocumentStateChangeResponse>(response);
        }
    }
}
