/*
 * MyInvois Middleware Gateway
 *
 * Open-source middleware gateway for Malaysia's MyInvois e-invoicing system. Provides a simplified REST API layer between applications and the official LHDN MyInvois API.  **Note**: This is an unofficial community project. See DISCLAIMER.md. 
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using MyInvois.Sdk.Client;
using MyInvois.Sdk.Api;
// uncomment below to import models
//using MyInvois.Sdk.Model;

namespace MyInvois.Sdk.Test.Api
{
    /// <summary>
    ///  Class for testing SessionsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SessionsApiTests : IDisposable
    {
        private SessionsApi instance;

        public SessionsApiTests()
        {
            instance = new SessionsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SessionsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SessionsApi
            //Assert.IsType<SessionsApi>(instance);
        }

        /// <summary>
        /// Test CreateSession
        /// </summary>
        [Fact]
        public void CreateSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SessionCreateRequest sessionCreateRequest = null;
            //var response = instance.CreateSession(sessionCreateRequest);
            //Assert.IsType<Session>(response);
        }

        /// <summary>
        /// Test DeleteSession
        /// </summary>
        [Fact]
        public void DeleteSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //instance.DeleteSession(sessionId);
        }

        /// <summary>
        /// Test GetSession
        /// </summary>
        [Fact]
        public void GetSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sessionId = null;
            //var response = instance.GetSession(sessionId);
            //Assert.IsType<Session>(response);
        }
    }
}
